name: ISCAN MARS AI API container

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    outputs:
      full_tag: ${{ steps.set-vars.outputs.full_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set lowercase image name and tag
        id: set-vars
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          TAG="addeddeployyml"
          FULL_TAG="$IMAGE_NAME:$TAG"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "FULL_TAG=$FULL_TAG" >> $GITHUB_ENV
          echo "full_tag=$FULL_TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image with tag: $FULL_TAG"
          docker build -t $FULL_TAG .

      - name: Push Docker image
        run: docker push $FULL_TAG

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ needs.build-and-publish.outputs.full_tag }}
            docker stop test-backend || true
            docker rm test-backend || true
            docker run -d --name test-backend -p 8000:8000 ${{ needs.build-and-publish.outputs.full_tag }}
